# Generated by Django 4.1.3 on 2022-12-22 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_feedback_replay_alter_feedback_user_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_payment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
